micronaut:
  application:
    name: app
  security:
    enabled: true
    token:
      jwt:
        enabled: true
        claims-validators:
          issuer: https://dev-06bzs1cu.us.auth0.com/
        signatures:
          jwks:
            okta:
              url: https://dev-06bzs1cu.us.auth0.com/.well-known/jwks.json
netty:
  default:
    allocator:
      max-order: 3
